server:
  port: 8080
  servlet:
    context-path: /warehouse

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Warehouse"
    username: root
    password: sa130220
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "AHaGZCtFmdGkRWd2X0kdnE7GPkV9dFHP9i0qfSeOU+LkndFFegV9HR5Xdzoqq5T2"
  valid-duration: 36000
  refreshable-duration: 360000