server:
  port: 8080
  servlet:
    context-path: /warehouse

spring:
  datasource:
    url: "jdbc:mysql://mysql-c9616c2-fpt-cfca.f.aivencloud.com:19031/warehouse_phone"
    username: avnadmin
    password: AVNS_q1b9SVJ1ojNK_sV6Ptj
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  cloud:
    name: dpf4ph1qu
  api:
    key: 756234473817482
    secret: T5qQXodnthydHuSyQYrF-xk98Eo

jwt:
  signerKey: "AHaGZCtFmdGkRWd2X0kdnE7GPkV9dFHP9i0qfSeOU+LkndFFegV9HR5Xdzoqq5T2"
  valid-duration: 36000
  refreshable-duration: 360000
