server:
  port: 8080
  servlet:
    context-path: /warehouse

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Warehouse"
    username: root
    password: 121121

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "AHaGZCtFmdGkRWd2X0kdnE7GPkV9dFHP9i0qfSeOU+LkndFFegV9HR5Xdzoqq5T2"
  valid-duration: 36000
  refreshable-duration: 360000